In [75]:
import pandas as pd
import numpy as np

In [76]:
data = pd.read_csv("iris.csv")

In [77]:
x = data.drop(['Species','Id'], axis=1)
x.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [78]:
y = data['Species']
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [79]:
x.sample(5)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
130            7.4           2.8            6.1           1.9
139            6.9           3.1            5.4           2.1
109            7.2           3.6            6.1           2.5
138            6.0           3.0            4.8           1.8
106            4.9           2.5            4.5           1.7

In [80]:
y.sample(5)

34         Iris-setosa
53     Iris-versicolor
132     Iris-virginica
128     Iris-virginica
122     Iris-virginica
Name: Species, dtype: object

In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [82]:
from sklearn.svm import SVC
model = SVC(C=0.1, kernel='rbf')

In [83]:
model.fit(x_train, y_train)

SVC(C=0.1)

In [84]:
model.score(x_test, y_test)

0.8444444444444444

In [85]:
from sklearn.svm import SVC
model = SVC(C=1, kernel='poly')

In [86]:
model.fit(x_train, y_train)

SVC(C=1, kernel='poly')

In [87]:
model.score(x_test, y_test)

0.9333333333333333

# GridSearchCV

In [88]:
from sklearn.model_selection import GridSearchCV

In [89]:
param_grid = {'C':[0.1, 1, 10],
             'kernel':['rbf', 'linear', 'poly']}

In [90]:
grid_search = GridSearchCV(estimator=model, param_grid=param_grid)
grid_search.fit(x_train, y_train)

GridSearchCV(estimator=SVC(C=1, kernel='poly'),
             param_grid={'C': [0.1, 1, 10],
                         'kernel': ['rbf', 'linear', 'poly']})

In [91]:
grid_search.best_params_

{'C': 0.1, 'kernel': 'poly'}

In [92]:
grid_search.score(x_test, y_test)

0.9111111111111111

# RandomizedSearchCV

In [93]:
from sklearn.model_selection import RandomizedSearchCV

In [94]:
param_dist = {'C':[0.1, 1, 10],
             'kernel':['rbf', 'linear', 'poly']}

In [95]:
randomized_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=5)
randomized_search.fit(x_train, y_train)

RandomizedSearchCV(estimator=SVC(C=1, kernel='poly'), n_iter=5,
                   param_distributions={'C': [0.1, 1, 10],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [96]:
randomized_search.best_params_

{'kernel': 'linear', 'C': 1}

In [97]:
randomized_search.score(x_test, y_test)

0.9555555555555556

In [121]:
randomized_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=8)
randomized_search.fit(x_train, y_train)

RandomizedSearchCV(estimator=SVC(C=1, kernel='poly'), n_iter=8,
                   param_distributions={'C': [0.1, 1, 10],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [122]:
randomized_search.best_params_

{'kernel': 'rbf', 'C': 10}

In [123]:
randomized_search.score(x_test, y_test)

0.9777777777777777